CREATE TABLE IF NOT EXISTS sale (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL UNIQUE,
    capienza INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS fasce_orarie (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    prezzo NUMERIC(10,2) NOT NULL
);

CREATE TABLE IF NOT EXISTS films (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titolo VARCHAR(255) NOT NULL,
    genere VARCHAR(255) NOT NULL,
    anno INTEGER NOT NULL,
    durata_minuti INTEGER NOT NULL,
    image_url VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS admin_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS programmazioni (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_id BIGINT NOT NULL,
    sala_id BIGINT NOT NULL,
    fascia_oraria_id BIGINT NOT NULL,
    orario_inizio TIME NOT NULL,
    data_inizio_programmazione DATE NOT NULL,
    data_fine_programmazione DATE NOT NULL,
    CONSTRAINT fk_programmazioni_film FOREIGN KEY (film_id) REFERENCES films(id),
    CONSTRAINT fk_programmazioni_sala FOREIGN KEY (sala_id) REFERENCES sale(id),
    CONSTRAINT fk_programmazioni_fascia FOREIGN KEY (fascia_oraria_id) REFERENCES fasce_orarie(id),
    CONSTRAINT uk_sala_fascia UNIQUE (sala_id, fascia_oraria_id),
    CONSTRAINT uk_film_fascia UNIQUE (film_id, fascia_oraria_id)
);

CREATE TABLE IF NOT EXISTS prenotazioni (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_cliente VARCHAR(100) NOT NULL,
    email_cliente VARCHAR(150) NOT NULL,
    numero_posti INTEGER NOT NULL,
    data_spettacolo DATE NOT NULL,
    created_at TIMESTAMP NOT NULL,
    codice_prenotazione VARCHAR(50) NOT NULL UNIQUE,
    stato VARCHAR(20) NOT NULL,
    programmazione_id BIGINT NOT NULL,
    CONSTRAINT fk_prenotazioni_programmazione FOREIGN KEY (programmazione_id) REFERENCES programmazioni(id)
);
